package com.malikjones.sniperasm.report

import com.malikjones.sniperasm.data.db.entities.Finding
import com.malikjones.sniperasm.data.db.entities.HostWithDetails
import com.malikjones.sniperasm.data.db.entities.ScanSession
import com.malikjones.sniperasm.data.db.entities.Severity
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object ReportGenerator {

    fun generateHtml(session: ScanSession, hosts: List<HostWithDetails>): String {
        val sb = StringBuilder()
        sb.append("<!DOCTYPE html><html><head><meta charset='utf-8'><title>SniperASM Report</title>")
        sb.append(styles())
        sb.append("</head><body>")
        sb.append("<h1>SniperASM Scan Report</h1>")
        sb.append("<p class='meta'>Target: ${escape(session.targetSpec)}<br/>")
        sb.append("Port list: ${escape(session.portListLabel)}<br/>")
        sb.append("Started: ${formatDate(session.startedAt)}<br/>")
        session.finishedAt?.let { sb.append("Finished: ${formatDate(it)}<br/>") }
        sb.append("Status: ${session.status}</p>")

        val allFindings = hosts.flatMap { it.findings }
        sb.append(summarySection(allFindings))

        hosts.filter { it.host.isUp }.forEach { hostDetail ->
            sb.append(hostSection(hostDetail))
        }

        sb.append("<p class='footer'>Generated by SniperASM for authorized security testing only.</p>")
        sb.append("</body></html>")
        return sb.toString()
    }

    private fun summarySection(findings: List<Finding>): String {
        val sb = StringBuilder("<h2>Summary</h2><div class='summary'>")
        for (sev in Severity.entries) {
            val count = findings.count { it.severity == sev }
            sb.append("<span class='badge ${sev.name.lowercase(Locale.US)}'>${sev.name}: $count</span>")
        }
        sb.append("</div>")
        return sb.toString()
    }

    private fun hostSection(detail: HostWithDetails): String {
        val sb = StringBuilder()
        sb.append("<h2>Host: ${escape(detail.host.ip)}</h2>")
        sb.append("<table><tr><th>Port</th><th>Service</th><th>Product</th><th>Version</th></tr>")
        detail.ports.sortedBy { it.port }.forEach { p ->
            sb.append("<tr><td>${p.port}/${escape(p.protocol)}</td><td>${escape(p.service ?: "-")}</td>")
            sb.append("<td>${escape(p.product ?: "-")}</td><td>${escape(p.version ?: "-")}</td></tr>")
        }
        sb.append("</table>")

        if (detail.findings.isNotEmpty()) {
            sb.append("<h3>Findings</h3><ul class='findings'>")
            detail.findings.sortedBy { severityOrder(it.severity) }.forEach { f ->
                sb.append("<li class='finding ${f.severity.name.lowercase(Locale.US)}'>")
                sb.append("<strong>[${f.severity}] ${escape(f.title)}</strong><br/>")
                sb.append(escape(f.description))
                f.cve?.let { sb.append("<br/><em>${escape(it)}</em>") }
                f.recommendation?.let { sb.append("<br/>Recommendation: ${escape(it)}") }
                sb.append("</li>")
            }
            sb.append("</ul>")
        }
        return sb.toString()
    }

    private fun severityOrder(s: Severity) = when (s) {
        Severity.CRITICAL -> 0
        Severity.HIGH -> 1
        Severity.MEDIUM -> 2
        Severity.LOW -> 3
        Severity.INFO -> 4
    }

    private fun formatDate(millis: Long): String =
        SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US).format(Date(millis))

    private fun escape(s: String): String = s
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\"", "&quot;")

    private fun styles(): String = """
        <style>
        body { font-family: -apple-system, Roboto, sans-serif; margin: 24px; color: #1a1a1a; }
        h1 { color: #0D1117; }
        .meta { color: #555; font-size: 14px; }
        table { border-collapse: collapse; width: 100%; margin-bottom: 16px; }
        th, td { border: 1px solid #ddd; padding: 6px 10px; text-align: left; font-size: 14px; }
        th { background: #0D1117; color: #39FF88; }
        .summary .badge { display: inline-block; padding: 4px 10px; margin-right: 6px; border-radius: 12px; font-size: 12px; color: white; }
        .critical { background: #7a0916; } .high { background: #c1121f; } .medium { background: #e07a00; }
        .low { background: #2a7de1; } .info { background: #6c757d; }
        ul.findings { list-style: none; padding: 0; }
        ul.findings li { border-left: 4px solid #999; padding: 8px 12px; margin-bottom: 8px; background: #f7f7f8; font-size: 14px; }
        ul.findings li.critical { border-color: #7a0916; } ul.findings li.high { border-color: #c1121f; }
        ul.findings li.medium { border-color: #e07a00; } ul.findings li.low { border-color: #2a7de1; }
        ul.findings li.info { border-color: #6c757d; }
        .footer { margin-top: 24px; font-size: 12px; color: #888; }
        </style>
    """.trimIndent()
}
